### ISSUE TITLE
PIO source?

### ISSUE THREAD

**Issue by DavidBuchanan314** [tierneytim/Pico-USB-audio#19]
The file [pdm.pio.h](https://github.com/tierneytim/Pico-USB-audio/blob/main/SDM/src/pdm.pio.h) is present, but it's a generated file - do you still have the original source?

**Comment by tierneytim** [comment]
Hi, there is not a source file (even though it does say autogenerated it kind of wasn't)... The file was written by  copying and pasting from other examples and using the  [pioasm online tool](https://wokwi.com/tools/pioasm) to lookup the relevant instructions that are then hardcoded into the file.

**Comment by DavidBuchanan314** [comment]
thanks!
