### ISSUE TITLE
Incorrect include in usb-device.c

### ISSUE THREAD

**Issue by dinther** [tierneytim/Pico-USB-audio#8]
the file usb-device.c contains:
```
#include "pico\fix\rp2040_usb_device_enumeration.h"
```
At compile time using pico-sdk version 1.3.0, this file can not be found. After trying all kinds of ways eventually I tried to just delete the include and that worked.
Compile went through and more importantly, the program works.

[edit]  Since then I found the official fix with includes that missing file here. 
https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2_common/pico_fix

But I have no idea how to get that included in the build.

**Comment by tierneytim** [comment]
thanks for this but the intricacies of the pico-sdk have become too tricky to support. Tt is now an Arduino only library.
